package com.sonicmusic.app.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Sonic fallback palette (used when dynamic color is unavailable/disabled).
val SonicLightPrimary = Color(0xFF3059C5)
val SonicLightOnPrimary = Color(0xFFFFFFFF)
val SonicLightPrimaryContainer = Color(0xFFDCE1FF)
val SonicLightOnPrimaryContainer = Color(0xFF00174B)

val SonicLightSecondary = Color(0xFF555F7A)
val SonicLightOnSecondary = Color(0xFFFFFFFF)
val SonicLightSecondaryContainer = Color(0xFFDCE3F9)
val SonicLightOnSecondaryContainer = Color(0xFF121C33)

val SonicLightTertiary = Color(0xFF006B57)
val SonicLightOnTertiary = Color(0xFFFFFFFF)
val SonicLightTertiaryContainer = Color(0xFF84F8DA)
val SonicLightOnTertiaryContainer = Color(0xFF002019)

val SonicLightError = Color(0xFFBA1A1A)
val SonicLightOnError = Color(0xFFFFFFFF)
val SonicLightErrorContainer = Color(0xFFFFDAD6)
val SonicLightOnErrorContainer = Color(0xFF410002)

val SonicLightBackground = Color(0xFFFBF8FF)
val SonicLightOnBackground = Color(0xFF1B1B21)
val SonicLightSurface = Color(0xFFFBF8FF)
val SonicLightOnSurface = Color(0xFF1B1B21)
val SonicLightSurfaceVariant = Color(0xFFE2E1EC)
val SonicLightOnSurfaceVariant = Color(0xFF45464F)
val SonicLightOutline = Color(0xFF757780)
val SonicLightOutlineVariant = Color(0xFFC5C5D0)
val SonicLightScrim = Color(0xFF000000)
val SonicLightInverseSurface = Color(0xFF303038)
val SonicLightInverseOnSurface = Color(0xFFF2F0FA)
val SonicLightInversePrimary = Color(0xFFB7C4FF)
val SonicLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val SonicLightSurfaceContainerLow = Color(0xFFF6F2FA)
val SonicLightSurfaceContainer = Color(0xFFF0ECF4)
val SonicLightSurfaceContainerHigh = Color(0xFFEAE7EF)
val SonicLightSurfaceContainerHighest = Color(0xFFE5E1E9)

val SonicDarkPrimary = Color(0xFFB7C4FF)
val SonicDarkOnPrimary = Color(0xFF002B79)
val SonicDarkPrimaryContainer = Color(0xFF0F43AB)
val SonicDarkOnPrimaryContainer = Color(0xFFDCE1FF)

val SonicDarkSecondary = Color(0xFFC0C7DD)
val SonicDarkOnSecondary = Color(0xFF273149)
val SonicDarkSecondaryContainer = Color(0xFF3D475F)
val SonicDarkOnSecondaryContainer = Color(0xFFDCE3F9)

val SonicDarkTertiary = Color(0xFF67DBBF)
val SonicDarkOnTertiary = Color(0xFF00382C)
val SonicDarkTertiaryContainer = Color(0xFF005140)
val SonicDarkOnTertiaryContainer = Color(0xFF84F8DA)

val SonicDarkError = Color(0xFFFFB4AB)
val SonicDarkOnError = Color(0xFF690005)
val SonicDarkErrorContainer = Color(0xFF93000A)
val SonicDarkOnErrorContainer = Color(0xFFFFDAD6)

val SonicDarkBackground = Color(0xFF111318)
val SonicDarkOnBackground = Color(0xFFE4E2EB)
val SonicDarkSurface = Color(0xFF111318)
val SonicDarkOnSurface = Color(0xFFE4E2EB)
val SonicDarkSurfaceVariant = Color(0xFF45464F)
val SonicDarkOnSurfaceVariant = Color(0xFFC5C5D0)
val SonicDarkOutline = Color(0xFF8F909A)
val SonicDarkOutlineVariant = Color(0xFF45464F)
val SonicDarkScrim = Color(0xFF000000)
val SonicDarkInverseSurface = Color(0xFFE4E2EB)
val SonicDarkInverseOnSurface = Color(0xFF303038)
val SonicDarkInversePrimary = Color(0xFF3059C5)
val SonicDarkSurfaceContainerLowest = Color(0xFF0D0E13)
val SonicDarkSurfaceContainerLow = Color(0xFF1A1B20)
val SonicDarkSurfaceContainer = Color(0xFF1E1F25)
val SonicDarkSurfaceContainerHigh = Color(0xFF282A2F)
val SonicDarkSurfaceContainerHighest = Color(0xFF33353A)
